<?php

namespace AddressBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    
    public function sortPeopleByName($userId){

        $people = $this->getEntityManager()->createQuery(
        'SELECT p FROM AddressBookBundle:Person p WHERE p.user = :userId ORDER BY p.name'
        )->setParameter('userId', $userId)
        ->getResult();
        
        return $people;
    }
}
